CREATE TABLE BOOKS155
(
BNO INT PRIMARY KEY,
BNAME VARCHAR NOT NULL,
WRITER VARCHAR,
ISBN VARCHAR CHECK(LENGTH(ISBN)=7) UNIQUE,
QT INT,
CONSTRAINT QT_C CHECK(QT>=0)
);

CREATE TABLE READER155
(
RNO INT PRIMARY KEY,
RNAME VARCHAR NOT NULL,
RSEX CHAR(2) CHECK(RSEX IN ('男','女')),
RAGE INT,
RADDR VARCHAR
);

CREATE TABLE BR155
(
BNO INT,
RNO INT,
BRDAY DATE,
BRQT INT,
CONSTRAINT PK_BR PRIMARY KEY(BNO,RNO),
CONSTRAINT BR_FKBNO FOREIGN KEY(BNO) REFERENCES BOOKS155(BNO),
CONSTRAINT BR_FKRNO FOREIGN KEY(RNO) REFERENCES READER155(RNO)
);